package br.com.intelector.testeui;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class FormularioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void formulario() {
    driver.get("https://accounts.seetest.io/signup?source=www.google.com");
    driver.manage().window().setSize(new Dimension(1882, 789));
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("THIAGO ALESSANDRO FARIAS");
    driver.findElement(By.id("lastname")).sendKeys("SANTOS");
    driver.findElement(By.cssSelector(".form-group:nth-child(2)")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("thiago.alessandro@totvs.com.br");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("SH2RBpeRx9fq4s8");
    driver.findElement(By.cssSelector(".text-center > .row:nth-child(3)")).click();
  }
}
